alias ll='ls -ltr'
alias ls='ls -F'
alias l.='ls -d .*'
alias l='ls -F'
alias sl='ls -F'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias mkdir='mkdir -pv'
alias h='history'
alias grep='grep --color=auto'
alias py2='python'
alias py='python3.6'
alias gitdir='cd /bb/nlp/table/usr/kwong487'
alias expdir='cd /bb/nlp/table/experiments'
alias mine='ls -ltr /bb/nlp/table/experiments | grep --color=never kwong487'
alias less='less -N'
alias gzless='gzless -N'
alias latest='cd `ls -1tr | grep kwong487 | tail -1`/end'
alias expdiff='~/expdiff'
alias expdiff_t='~/expdiff_t'
alias exp='~/exp'
alias ag='ag --ignore tags'
alias ff='~/ff'
alias wsp='cd ~/WSL'
alias g++='g++ -std=c++11'
alias downloads='cd /c/Users/WongKevin/Downloads/'
alias docs='cd /c/Users/WongKevin/Documents/'
alias g17='g++ -std=gnu++17'
alias kcmd='katie --namespace s-ainlu hdfs --identity ai-nlu-dnj2-gen'
